image: debian:latest
variables:
  three: threee
  variable_expansion_one: works
  variable_expansion_two: works
stages:
  - test

.outside_anchor: &outside_anchor
  image: fedora:latest

.inside_anchor: &inside_anchor
  - two

miniexec-example-1:
  stage: test
  script: |
    sleep 2
    echo "Thanks for using MiniExec!"

miniexec-example-2:
  stage: test
  script: |
    sleep 2
    cat /build/README.md

miniexec-example-3:
  stage: test
  script: |
    sleep 2
    echo "Here are your environment variables:"
    echo "$MY_USER"
    echo "$MY_KEY"

basic-test:
  stage: test
  image: ubuntu:latest
  script: |
    echo 'hello'
    echo 'goodbye'

no-image-test:
  stage: test
  script: "echo 'hello'"

before-after-script-test:
  stage: test
  before_script: one
  after_script: four
  script: |
    two
    three

anchor-test:
  stage: test
  <<: *outside_anchor
  script:
    - one
    - *inside_anchor
    - three

variables-test:
  stage: test
  variables:
    one: 1
    two: ttwwoo
  script: 'hello, world'

internal-variable-expansion-test:
  stage: test
  variables:
    foo: ${variable_expansion_one}
    bar: $variable_expansion_two
  script: echo "$foo" "$bar"

default-mount-test:
  stage: test
  script: |
    sleep 2
    ls /gitlab/.gitlab-ci.yml
